### ISSUE TITLE
No API Key was provided and no API Key could be found for ... To save an API Key for a source use the 'setApiKey' command

### ISSUE THREAD

**Issue by abakumov-v** [tanaka-takayoshi/nuget-publish-to-github-packages-action#3]
Hi!

Thank you for this cool and simple action! When I'm tryed use it, I'm getting an error:

```
Run tanaka-takayoshi/nuget-publish-to-github-packages-action@v2.1
/opt/hostedtoolcache/dncs/3.1.301/x64/dotnet nuget push ./out/*.nupkg --source github --skip-duplicate
warn : No API Key was provided and no API Key could be found for 'https://nuget.pkg.github.com/my-owner'. To save an API Key for a source use the 'setApiKey' command.
Pushing Core.Exceptions.0.0.1.nupkg to 'https://nuget.pkg.github.com/my-owner'...
  PUT https://nuget.pkg.github.com/my-owner/
  NotFound https://nuget.pkg.github.com/my-owner/ 247ms
error: Response status code does not indicate success: 404 (Not Found).


Usage: dotnet nuget push [arguments] [options]

Arguments:
  [root]  Specify the path to the package and your API key to push the package to the server.

Options:
  -h|--help                      Show help information
  --force-english-output         Forces the application to run using an invariant, English-based culture.
  -s|--source <source>           Package source (URL, UNC/folder path or package source name) to use. Defaults to DefaultPushSource if specified in NuGet.Config.
  -ss|--symbol-source <source>   Symbol server URL to use.
  -t|--timeout <timeout>         Timeout for pushing to a server in seconds. Defaults to 300 seconds (5 minutes).
  -k|--api-key <apiKey>          The API key for the server.
  -sk|--symbol-api-key <apiKey>  The API key for the symbol server.
  -d|--disable-buffering         Disable buffering when pushing to an HTTP(S) server to decrease memory usage.
  -n|--no-symbols                If a symbols package exists, it will not be pushed to a symbols server.
  --no-service-endpoint          Does not append "api/v2/package" to the source URL.
  --interactive                  Allow the command to block and require manual action for operations like authentication.
  --skip-duplicate               If a package and version already exists, skip it and continue with the next package in the push, if any.
(node:2721) UnhandledPromiseRejectionWarning: TypeError: (s || "").replace is not a function
    at escapeData (/home/runner/work/_actions/tanaka-takayoshi/nuget-publish-to-github-packages-action/v2.1/dist/index.js:1268:10)
```

My workflow file is:
```yml
name: .NET Core

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  # GitHub Packages:
  NUGET_URL: https://nuget.pkg.github.com/my-owner/index.json

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1.5.0
        # env:
        #   NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        #   # This does not work - runner need to only GITHUB_TOKEN
        #   # NUGET_AUTH_TOKEN: ${{secrets.PACKAGES_READ_WRITE_TOKEN}}
        with:
          dotnet-version: 3.1.301
          # source-url: https://nuget.pkg.github.com/my-owner/index.json

      - name: Set version
        run: echo "::set-env name=VERSION::$(cat .version)"

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Pack
        run: dotnet pack -c Release /p:PackageVersion=$VERSION -o ./out --no-restore -v normal

      # - name: Publish
      #   env:
      #     NUGET_SOURCE: "https://nuget.pkg.github.com/my-owner/index.json"
      #     # NUGET_DEPLOY_TOKEN: ${{secrets.PACKAGES_READ_WRITE_TOKEN}}
      #     NUGET_DEPLOY_TOKEN: ${{secrets.GITHUB_TOKEN}}
      #   run: dotnet nuget push "./out/Core.Exceptions.$VERSION.nupkg" -s $NUGET_SOURCE -k $NUGET_DEPLOY_TOKEN

      - name: Publish
        uses: tanaka-takayoshi/nuget-publish-to-github-packages-action@v2.1
        with:
          nupkg-path: "./out/*.nupkg"
          repo-owner: "my-owner"
          gh-user: "abakumov-v"
          token: ${{ secrets.GITHUB_TOKEN }}

```

What I'm doing wrong?

P.S. Repo is private.
